package by.epam.training.travelpackage.command;

public enum CommandType {

    SELECT_BY_AIRPLANE, SELECT_BY_BUS,SELECT_BY_TRAIN, SELECT_BY_CRUISE_SHIP, SELECT_BY_NUTRITION_RO,
    SORT_INCREASE_BY_DURATION, SORT_DESCREASE_BY_DURATION,  SORT_INCREASE_BY_PRICE_DURATION, SELECT_BY_TOUR_TYPE_RELAX

}
